### ISSUE TITLE
FYI, list of generals.io clone repo

### ISSUE THREAD

**Issue by makerjackie** [GenniaApp/Gennia#1]
A collection of generals.io clone repo

https://github.com/GenniaApp/Gennia
https://github.com/fluffybeastgames/MadJS and the demo https://fluffybeast.io/mad/
https://github.com/dhyegocalota/generals-io-webapp
https://github.com/seveibar/boxarmy
https://github.com/Toseic/Generals-chess
https://github.com/little-dude/generals-rs
https://github.com/montsilen/generals
https://github.com/zidinghe/generals-AI
https://github.com/neolefty/hexerals
https://github.com/seveibar/boxarmy
https://github.com/sziffera/Generals.io
https://github.com/jlammilliman/Generals.io.2.0

**Comment by Reqwey** [comment]
Hello @Jackiexiao! I'd appreciate it if you can join our team :)

**Comment by makerjackie** [comment]
sure, I have been chat with madjs(another clone of generals.io) developer these days, glad to join your team

**Comment by makerjackie** [comment]
another generals.io clone game:

https://github.com/By-Ha/Checkmate which website is https://kana.byha.top:444/ , [video](https://www.bilibili.com/video/BV1yo4y1f7n9/)

**Comment by makerjackie** [comment]
a offline generals.io using Qt : https://github.com/x405x/Generals.OI @x405x
A new version of gennia using react/nextjs/socket/express: https://github.com/GenniaApp/GenniaServer2

**Comment by makerjackie** [comment]
moving to : https://github.com/GenniaApp/GenniaServer2/discussions/3
